AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Restauranto-api

  AWS SAM CloudFormation Stack for Restauranto API

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  Env:
    Type: String
    AllowedValues:
      - dev
      - staging
      - prod

Resources:
  ########################
  #
  # Lambda Functions
  #
  ########################
  PlacesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/places/
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
        Nearby:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /places/nearby
            Method: get
        Search:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /places/search
            Method: get
        Details:
          Type: Api
          Properties:
            Path: /places
            Method: get
      Layers:
        - !Ref UtilsLayer
      Environment:
        Variables:
          NODE_ENV: !Ref Env
      Policies:
        - Statement:
          - Sid: SSMDescribeParametersPolicy
            Effect: Allow
            Action:
              - ssm:DescribeParameters
            Resource: '*'
          - Sid: SSMGetParameterPolicy
            Effect: Allow
            Action:
              - ssm:GetParameters
              - ssm:GetParameter
            Resource: '*'

  ########################
  #
  # Layers
  #
  ########################
  UtilsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: Utils
      Description: Shared utilities for Lambdas
      ContentUri: src/layers
      CompatibleRuntimes:
        - nodejs12.x


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SampleApi:
    Description: "API Gateway endpoint URL for Prod stage for Places endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/places/"
  PlacesFunction:
    Description: "Places Lambda Function ARN"
    Value: !GetAtt PlacesFunction.Arn
  PlacesFunctionIamRole:
    Description: "Implicit IAM Role created for Places function"
    Value: !GetAtt PlacesFunctionRole.Arn
